title: "GR-CITRUS & WA-MIKANを使いこなす (2023年版)"
summary: "2023年の梅雨真っ只中、突如秋月電子で大量放出されたGR-CITRUS & WA-MIKAN。発売開始から7年経ったこのボードをどのようにしたら使いこなせるかを見ていきます。"
topics: ["mruby", "がじぇっとるねさす", "電子工作", "ESP8266"]
published: false
price: 0 # 有料の場合200〜5000
# 本に含めるチャプターを順番に並べましょう
chapters:
  - 01_intro
  - 02_devenv
  - 03_i2c_lcd
  - 04_i2c_aht25
  - 05_i2c_bme680
  - 06_wa_mikan_wifi
  - 07_wa_mikan_microsd
  - 08_arduino_like_sketch
  - 09_compile_ruby_firmware
  - 10_wa_mikan_only1
  - 11_wa_mikan_only2
